print("how variables keep track of things like adding and removing doller from a wallet")

wallet = 3
wallet= wallet+  2
wallet = wallet - 1 
print(wallet)

print("THINGS ARE DIFFERENT FROM HERE")

name = "account name :"
name = name + "satyam"
name = name  + " verma"

print(name)

print("another thing")

speed = 100
speed = speed + 1
print(speed)





print("2nd part is about few operators help us to code faster")


likes  = 5 
likes = likes + 1
print(likes)

print("6 likes will be the output but now we learn the another way of doing it")

sales = 5 
sales += 10
print(sales)
print('same for others i.e +_*/')

